language: java
jdk:
  - openjdk8

sudo: required

branches:
  only:
    - deploy-ec2

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle

# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"

before_deploy:
#  - zip -r eatgo *
#  - mkdir -p deploy
#  - mv eatgo.zip deploy/eatgo.zip
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp eatgo-api/build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/eatgo.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hol-eatgo
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      - branch: deploy-ec2

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hol-eatgo
    key: eatgo.zip
    bundle_type: zip
    application: hol-eatgo-deploy
    deployment_group: hol-eatgo-deploymentgroup1
    region: us-east-1
    wait-until-deployed: true
    on:
      - branch: deploy-ec2

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - leftwing871@gmail.com



