language: java
jdk:
  - openjdk8

sudo: required

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle

# clean 후 Build (Build시 자동으로 test 수행)
script: "./gradlew clean build"

before_deploy:
  - zip -r eatgo *
  - mkdir -p build-backend
  - mv eatgo.zip build-backend/eatgo.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: hol-eatgo
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: build-backend
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - leftwing871@gmail.com

