#05-mysql-clusterip-service-nodeport.yml
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-nodeport
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    type: app
    service: mysql
