---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: ap-northeast-2
  version: "1.17"

availabilityZones: ["ap-northeast-2a", "ap-northeast-2b", "ap-northeast-2c"]

managedNodeGroups:
- name: nodegroup
  instanceType: t3.large
  minSize: 2
  maxSize: 8  
  desiredCapacity: 3
  labels:
    nodegroup-type: eksworkshop
  ssh:
    allow: true
    publicKeyName: eksworkshop

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:ap-northeast-2:268114937024:key/c1e17589-0053-45ef-8476-004947014813
